[project]
name = "stream-station"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "pyyaml>=6.0.2",
    "uvicorn>=0.34.3",
    "validators>=0.35.0",
    "yt-dlp>=2025.6.9",
]
